import { useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, CircleDot, Clock3, FileText, Filter, MoreHorizontal, Plus, Search, ShieldCheck, Wrench } from 'lucide-react'
import { Badge, Button, Card, PageHeading } from '../components/ui'
import { useLocalFix } from '../state/LocalFixContext'

export default function CasesPage() {
  const { cases, demoMode } = useLocalFix()
  const [selectedId, setSelectedId] = useState(cases[0]?.id ?? '')
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState<'All cases' | 'Resolved' | 'In progress'>('All cases')
  const [savedKnowledge, setSavedKnowledge] = useState(false)
  const navigate = useNavigate()
  const filtered = useMemo(() => cases.filter(item => {
    const matchesQuery = `${item.id} ${item.equipment} ${item.fault} ${item.diagnosis}`.toLowerCase().includes(query.toLowerCase())
    return matchesQuery && (filter === 'All cases' || item.status === filter)
  }), [cases, query, filter])
  const selected = filtered.find(item => item.id === selectedId) ?? filtered[0]
  return <div className="cases-page">
    <PageHeading eyebrow="LOCAL FIELD KNOWLEDGE" title="Service cases" subtitle="A searchable record of observations, procedures, and source-backed resolutions." action={<Button variant="primary" onClick={() => navigate('/diagnose')}><Plus size={15}/> New case</Button>}/>
    <div className="cases-toolbar"><div className="case-search"><Search size={15}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by case, asset, or fault…" aria-label="Search cases"/><kbd>⌘ K</kbd></div><div className="case-filters"><Filter size={14}/>{(['All cases', 'Resolved', 'In progress'] as const).map(item => <button key={item} className={filter === item ? 'filter-active' : ''} onClick={() => setFilter(item)}>{item}{item === 'All cases' && <span>{cases.length}</span>}</button>)}</div><button className="filter-more"><ChevronDown size={14}/> Date range</button></div>
    <div className="cases-layout"><section className="case-list-panel"><div className="case-list-heading"><span>CASES <b>{filtered.length}</b></span><button aria-label="More list options"><MoreHorizontal size={16}/></button></div><div className="case-list">{filtered.map(item => <button key={item.id} className={`case-list-item ${selected?.id === item.id ? 'selected' : ''}`} onClick={() => setSelectedId(item.id)}><div className="case-list-top"><span className="case-list-id">#{item.id}</span><Badge tone={item.status === 'Resolved' ? 'lime' : 'amber'}>{item.status}</Badge></div><div className="case-list-title">{item.fault} <span>·</span> {item.equipment}</div><p>{item.diagnosis}</p><div className="case-list-meta"><span><Clock3 size={12}/>{item.timestamp}</span><span><BookOpen size={12}/>{item.evidenceCount} sources</span></div></button>)}{filtered.length === 0 && <div className="empty-list"><Search size={18}/><b>No matching cases</b><span>Try another fault code or equipment model.</span></div>}</div><div className="case-list-foot"><ShieldCheck size={12}/> Stored locally on this device</div></section>
      <section className="case-detail-panel">{selected ? <><div className="case-detail-head"><div><div className="eyebrow">CASE OVERVIEW <span className="eyebrow-separator">/</span> #{selected.id}</div><h2>{selected.fault}<span className="detail-title-sep">·</span> {selected.diagnosis}</h2></div><div className="case-detail-actions"><button className="icon-button" aria-label="More case actions"><MoreHorizontal size={16}/></button><Button variant="secondary" size="small" onClick={() => navigate('/reports')}>Report <ArrowUpRight size={13}/></Button></div></div><div className="case-status-row"><Badge tone={selected.status === 'Resolved' ? 'lime' : 'amber'}><span className="status-badge-dot"/>{selected.status}</Badge><span><Wrench size={13}/>{selected.equipment} · Serial {selected.serialNumber ?? 'Not recorded'}</span><span><Clock3 size={13}/>{selected.duration}</span><span><CircleDot size={13}/>{selected.technician}</span></div><div className="case-detail-grid"><Card className="case-detail-card"><div className="detail-card-title"><span className="detail-card-icon orange"><CircleDot size={14}/></span><div><small>OBSERVED CONDITION</small><h3>{selected.simulated ? 'Display shows E07' : 'Observation record'}</h3></div></div>{selected.simulated ? <p>Motor feedback mismatch recorded on the fictional ACM-4200 demo asset. The synthetic model label is simulated.</p> : <p>{selected.observations?.length ? selected.observations.join(' · ') : 'No camera OCR observation is stored. Review the attached local manual evidence and technician notes.'}</p>}<div className="detail-card-tags">{selected.simulated ? <><Badge tone="red">E07</Badge><Badge tone="neutral">ACM-4200</Badge><Badge tone="neutral">SN-823919</Badge></> : <Badge tone="neutral">{selected.evidenceCount} source passages</Badge>}</div></Card><Card className="case-detail-card"><div className="detail-card-title"><span className="detail-card-icon lime"><Check size={14}/></span><div><small>SUPPORTED FINDING</small><h3>{selected.diagnosis}</h3></div></div>{selected.simulated ? <p>Service Manual 2026 associates E07 with motor-control feedback. Initial visual checks are documented in the evidence chain.</p> : <p>The selected finding is linked to these local source passages. Equipment identity remains unverified unless recorded separately.</p>}<Link to="/evidence" className="inline-source"><BookOpen size={13}/> 3 manual references <ArrowRight size={12}/></Link></Card></div>
        <Card className="case-timeline-card"><div className="case-timeline-header"><div><div className="eyebrow">CASE ACTIVITY</div><h3>Field timeline</h3></div><button className="icon-button" aria-label="More activity options"><MoreHorizontal size={16}/></button></div><div className="case-activity-list"><div className="case-activity-item"><span className="activity-node node-done"><Check size={11}/></span><div><b>Diagnosis started</b><p>{selected.observations?.join(' · ') || 'No camera/OCR observation was recorded.'}</p><small>LOCALFIX · 12 MIN AGO</small></div></div><div className="case-activity-item"><span className="activity-node node-done"><BookOpen size={10}/></span><div><b>Manual evidence attached</b><p>{selected.evidenceCount} manual source passages attached.</p><small>LOCAL RETRIEVAL · 9 MIN AGO</small></div></div><div className="case-activity-item"><span className="activity-node node-current"><Wrench size={10}/></span><div><b>{selected.status === 'Resolved' ? 'Procedure completed' : 'Procedure in progress'}</b><p>{selected.notes}</p><small>{selected.status.toUpperCase()} · {selected.timestamp.toUpperCase()}</small></div></div></div></Card><div className="case-detail-footer"><div><span className="case-footer-avatar">JD</span><span>Recorded by <b>{selected.technician}</b><small>{selected.simulated || demoMode ? 'DEMO RECORD · SIMULATED' : 'LOCAL CASE'}</small></span></div><div><button className={`knowledge-button ${savedKnowledge ? 'knowledge-saved' : ''}`} onClick={() => setSavedKnowledge(value => !value)}>{savedKnowledge ? <Check size={14}/> : <BookOpen size={14}/>} {savedKnowledge ? 'Saved as knowledge' : 'Save as knowledge'}</button><span className="case-date">{selected.timestamp}</span></div></div></> : <div className="case-detail-empty"><FileText size={24}/><b>Select a case</b><span>Choose a case to review its evidence and timeline.</span></div>}</section></div>
    <div className="cases-page-foot"><span><ShieldCheck size={13}/> Local case history · available offline</span><span>{cases.length} records <span>·</span> LocalFix Demo User <ChevronDown size={12}/></span></div>
  </div>
}
