import { ArrowRight, ArrowUpRight, AudioLines, BookOpen, Camera, Check, ChevronRight, Clock3, Cpu, HardDrive, LockKeyhole, MoveUpRight, Plus, ScanLine, ShieldCheck, Sparkles, WifiOff, Zap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { motion } from 'motion/react'
import { Card, Badge, Button, PageHeading, SectionTitle } from '../components/ui'
import { EquipmentArt } from '../components/EquipmentArt'
import { useLocalFix } from '../state/LocalFixContext'

function Metric({ label, value, foot }: { label: string; value: string; foot: string }) {
  return <div className="metric"><span className="metric-label">{label}</span><b>{value}</b><small>{foot}</small></div>
}

export default function HomePage() {
  const { demoMode, runtime, cases } = useLocalFix()
  return <div className="home-page">
    <PageHeading eyebrow="MONDAY, SEPTEMBER 29, 2026 · SHIFT A" title={<>Good morning, Jordan<span className="heading-period">.</span></>} subtitle="Your field workspace is ready. Local tools, manuals, and case history are available offline." action={<Button variant="secondary" onClick={() => window.location.href = '/cases'}><Clock3 size={15}/> View activity</Button>}/>
    <motion.section className="hero-card" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .35 }}>
      <div className="hero-copy"><div className="hero-kicker"><span className="hero-kicker-line"/> FIELD ASSISTANT <span className="hero-kicker-dot"/> READY</div><h2>Your next repair,<br/><span>with the evidence in view.</span></h2><p>Point your camera at the equipment. LocalFix reads the panel, finds the right manual passage, and guides each safe check.</p><div className="hero-actions"><Link className="button button-primary button-large" to="/diagnose"><Camera size={17}/> Start diagnosis <ArrowRight size={16}/></Link><Link className="button button-dark button-large" to="/diagnose?import=1"><Plus size={16}/> Import image</Link></div><div className="hero-assurances"><span><LockKeyhole size={13}/> Local by default</span><span><WifiOff size={13}/> Works offline</span><span><ShieldCheck size={13}/> Every answer cited</span></div></div>
      <div className="hero-art"><div className="art-grid"/><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><EquipmentArt compact/><div className="hero-art-label"><span className="art-status-dot"/><div><b>{demoMode ? 'ACM-4200 · DEMO' : 'SYNTHETIC EQUIPMENT ART'}</b><small>{demoMode ? 'INDUSTRIAL MOTOR CONTROLLER' : 'NOT A LIVE CAMERA DETECTION'}</small></div></div><div className="scan-line"/></div>
      <div className="hero-footer"><div className="hero-footer-left"><span className="hero-foot-icon"><ScanLine size={15}/></span><span><b>Ready to inspect</b><small>{demoMode ? 'DEMO WORKSPACE · SIMULATED INPUT' : 'LOCAL RUNTIME · CHECK MODEL STATUS'}</small></span></div><div className="hero-footer-right"><span className="signal-bars"><i/><i/><i/><i/></span><span>EDGE AI <b>{demoMode ? 'DEMO' : runtime.npu === 'active' ? 'NPU' : 'LOCAL'}</b></span></div></div>
    </motion.section>

    <div className="home-grid">
      <Card className="equipment-card"><SectionTitle action={<button className="text-action">Equipment registry <ArrowUpRight size={13}/></button>}>{demoMode ? 'Active equipment · demo' : 'Equipment registry'}</SectionTitle>{demoMode ? <><div className="equipment-summary"><div><div className="asset-tag"><span className="asset-lamp"/> DEMO ASSET</div><h3>ACM-4200</h3><p>Fictional industrial motor controller</p><div className="equipment-meta"><span><b>SN</b> 823919</span><span className="meta-divider"/><span>Sample site · Line 04</span></div></div><div className="needs-attention"><span className="attention-pulse"/><span><small>STATUS</small><b>Needs attention</b></span></div></div><div className="fault-strip"><div className="fault-code">E07</div><div className="fault-copy"><small>ACTIVE FAULT · SIMULATED</small><b>Motor feedback mismatch</b><span>Sample event · demo data</span></div><Link to="/diagnose" className="fault-open" aria-label="Open diagnosis"><ArrowUpRight size={16}/></Link></div></> : <div className="empty-asset"><div className="asset-tag">NO ACTIVE ASSET</div><h3>Equipment not verified</h3><p>Start a camera session or import a local image. A model label is shown only after a local detector confirms it.</p><Link to="/diagnose" className="inline-source">Start diagnosis <ArrowRight size={12}/></Link></div>}</Card>
      <Card className="runtime-card"><SectionTitle action={<Link className="icon-text-link" to="/reports?tab=runtime">Details <ArrowUpRight size={13}/></Link>}>Local AI runtime</SectionTitle><div className="runtime-card-head"><div className={`runtime-emblem ${!demoMode && runtime.npu === 'active' ? 'active' : ''}`}><Cpu size={19}/></div><div><small>INFERENCE BACKEND</small><b>{demoMode ? 'Demo simulation' : runtime.backend}</b></div><Badge tone={demoMode ? 'amber' : runtime.npu === 'active' ? 'lime' : 'neutral'}>{demoMode ? 'SIMULATED' : runtime.npu === 'active' ? 'NPU ACTIVE' : 'LOCAL'}</Badge></div><div className="runtime-metrics"><Metric label="VISION" value={demoMode ? '—' : `${runtime.latencyMs.vision ?? '—'}${runtime.latencyMs.vision ? ' ms' : ''}`} foot={demoMode ? 'No measurement' : runtime.models.vision === 'ready' ? 'Measured' : 'Model unavailable'}/><Metric label="OCR" value={demoMode ? '—' : `${runtime.latencyMs.ocr ?? '—'}${runtime.latencyMs.ocr ? ' ms' : ''}`} foot={demoMode ? 'No measurement' : runtime.models.ocr === 'ready' ? 'Measured' : 'Model unavailable'}/><Metric label="SPEECH" value={demoMode ? '—' : `${runtime.latencyMs.speech ?? '—'}${runtime.latencyMs.speech ? ' ms' : ''}`} foot={demoMode ? 'No measurement' : runtime.models.speech === 'ready' ? 'Measured' : 'Model unavailable'}/></div><div className="runtime-foot"><span><WifiOff size={13}/> Network <b>{runtime.network.toUpperCase()}</b></span><span><HardDrive size={13}/> Data <b>ON DEVICE</b></span></div></Card>
    </div>

    <div className="home-lower-grid">
      <Card className="recent-card"><SectionTitle action={<Link className="icon-text-link" to="/cases">All cases <ArrowRight size={13}/></Link>}>Recent cases</SectionTitle><div className="case-list-home">{cases.slice(0, 2).map((item, index) => <Link to="/cases" className="case-row-home" key={item.id}><div className={`case-icon ${index === 0 ? 'case-icon-lime' : ''}`}><Zap size={15}/></div><div className="case-row-copy"><div><b>#{item.id} <span>{item.fault}</span></b><Badge tone={item.status === 'Resolved' ? 'lime' : 'amber'}>{item.status}</Badge></div><p>{item.diagnosis}</p><small>{item.equipment} · {item.timestamp}{item.simulated ? ' · SIMULATED' : ''}</small></div><ChevronRight size={16} className="case-chevron"/></Link>)}</div><Link to="/cases" className="view-all-cases">Open case history <ArrowRight size={13}/></Link></Card>
      <Card className="privacy-card"><div className="privacy-top"><div className="privacy-icon"><ShieldCheck size={18}/></div><Badge tone="lime">LOCAL ONLY</Badge></div><h3>Your field data stays here.</h3><p>Images, voice, manuals, and inference remain on this device. LocalFix makes no cloud requests.</p><div className="privacy-lines"><div><span><Camera size={13}/> Images</span><b>THIS DEVICE</b><Check size={13}/></div><div><span><AudioLines size={13}/> Voice</span><b>THIS DEVICE</b><Check size={13}/></div><div><span><BookOpen size={13}/> Manuals</span><b>THIS DEVICE</b><Check size={13}/></div></div><div className="privacy-note"><LockKeyhole size={12}/> {demoMode ? 'Demo content is simulated and stored in this browser session.' : 'No external AI service is configured.'}</div></Card>
    </div>
    <div className="home-bottom-note"><Sparkles size={13}/><span>{demoMode ? 'Demo mode illustrates the workflow. Switch to Local Runtime to connect real device telemetry and installed models.' : 'Hardware acceleration is reported only when the local inference provider confirms it.'}</span><MoveUpRight size={13}/></div>
  </div>
}
